### PR TITLE
make lsp happy

### PR DESCRIPTION
**Pull request by yinghaoyu**
1. For `.clangd`, see also https://github.com/clangd/clangd/issues/662#issuecomment-1447233948.
2. `async_simple/Future.h` and `async_simple/Promise.h` include recursively.

### CODE REVIEW

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM.  Thanks.

Let's see if the CI feels good about it.

**Comment by ChuanqiXu9** [comment]
It looks like it is a breaking change to require the users to include `Promise.h` explicitly. This may be not good. Can we teach clangd to not complain about it?

Also the formatter looks not happy too.

**Comment by yinghaoyu** [comment]
`std::promise` as a friend class for `std::future`, both of them are in the same file. Emmmm, maybe it's a `breaking change`. Please ignore this commit.

**Comment by yinghaoyu** [comment]
My clang is out of date, so the formatter is not fit.

**Pull request closed without merging**
