### PR TITLE
add conan recipe

### PR DESCRIPTION
**Pull request by PikachuHyA**
## Why

Conan is a C/C++ Package Manager.

Support Conan to get more potential users

## What is changing

- add conan recipe `conanfile.py`

- update README

- add conan ci

### CODE REVIEW

**Comment by RainMark** [comment]
cool，can you add a related build test ci？

**Comment by PikachuHyA** [comment]
my pleasure

> cool，can you add a related build test ci？

**Comment by PikachuHyA** [comment]
conan ci added

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM.

**Pull request merged**
