### PR TITLE
feat: add `future::then` interface

### PR DESCRIPTION
**Pull request by 4kangjc**

### CODE REVIEW

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM. It may be better to mention this in docs.

**Comment by 4kangjc** [comment]
> LGTM. It may be better to mention this in docs.

I see.

**Comment by 4kangjc** [comment]
`async_simple_coro_test`卡死了一次
https://github.com/alibaba/async_simple/actions/runs/3692503582/jobs/6251463524
不知道为什么

**Review by ChuanqiXu9 — APPROVED** [review]

**Comment by 4kangjc** [comment]
> > https://github.com/alibaba/async_simple/actions/runs/3692503582/jobs/6251463524
> 
> hmmm 这种问题还挺难查。。

hmm确实

**Pull request merged**
